-- MySQL Script generated by MySQL Workbench
-- Mon May  1 09:49:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vikingsBeer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vikingsBeer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vikingsBeer` DEFAULT CHARACTER SET utf8 ;
USE `vikingsBeer` ;

-- -----------------------------------------------------
-- Table `vikingsBeer`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vikingsBeer`.`usuario` ;

CREATE TABLE IF NOT EXISTS `vikingsBeer`.`usuario` (
  `id` INT NOT NULL,
  `dt_nasc` DATE NULL,
  `nome` VARCHAR(250) NULL,
  `email` VARCHAR(250) NULL,
  `senha` VARCHAR(30) NULL,
  `creatime_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vikingsBeer`.`perfil_completo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vikingsBeer`.`perfil_completo` ;

CREATE TABLE IF NOT EXISTS `vikingsBeer`.`perfil_completo` (
  `id` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `Cpf` VARCHAR(45) NULL,
  `cep` DECIMAL(9) NULL,
  `endereco` VARCHAR(500) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(500) NULL,
  `cidade` VARCHAR(100) NULL,
  `foto_perfil` VARCHAR(100) NULL,
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `idUsuario_idx` (`id_usuario` ASC),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `vikingsBeer`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vikingsBeer`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vikingsBeer`.`carrinho` ;

CREATE TABLE IF NOT EXISTS `vikingsBeer`.`carrinho` (
  `id` INT NOT NULL,
  `id_perfil` INT NOT NULL,
  `status` INT NULL,
  `total_preco` DECIMAL(10,2) NULL,
  `entrega` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `vikingsBeer`.`perfil_completo` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vikingsBeer`.`type_beer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vikingsBeer`.`type_beer` ;

CREATE TABLE IF NOT EXISTS `vikingsBeer`.`type_beer` (
  `idtype_beer` INT NOT NULL,
  `name_type` VARCHAR(250) NULL,
  PRIMARY KEY (`idtype_beer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vikingsBeer`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vikingsBeer`.`produto` ;

CREATE TABLE IF NOT EXISTS `vikingsBeer`.`produto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `descricao` VARCHAR(1000) NULL,
  `preco` DECIMAL(10,2) NULL,
  `imagem` VARCHAR(500) NULL,
  `idtype_beer` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `Id_type_beer`
    FOREIGN KEY (`idtype_beer`)
    REFERENCES `vikingsBeer`.`type_beer` (`idtype_beer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vikingsBeer`.`pedido_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vikingsBeer`.`pedido_item` ;

CREATE TABLE IF NOT EXISTS `vikingsBeer`.`pedido_item` (
  `id_carrinho` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quant` VARCHAR(45) NULL,
  PRIMARY KEY (`id_carrinho`, `id_produto`),
  CONSTRAINT `id_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `vikingsBeer`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_carrinho`
    FOREIGN KEY (`id_carrinho`)
    REFERENCES `vikingsBeer`.`carrinho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;