-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 19:26:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `dtNasc` DATE NULL,
  `nameComplete` VARCHAR(250) NULL,
  `email` VARCHAR(250) NULL,
  `password` VARCHAR(30) NULL,
  `creatime_time` TIMESTAMP NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PerfilCompleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PerfilCompleto` (
  `idPerfil Completo` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `Cpf` VARCHAR(45) NULL,
  `cep` DECIMAL(9) NULL,
  `endereco` VARCHAR(500) NULL,
  `complemento` VARCHAR(500) NULL,
  `cidade` VARCHAR(100) NULL,
  `foto_perfil` VARCHAR(100) NULL,
  PRIMARY KEY (`idPerfil Completo`),
  INDEX `idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(1000) NULL,
  `harmonize` VARCHAR(500) NULL,
  `price` DECIMAL(100,2) NULL,
  `image` VARCHAR(500) NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrinho` (
  `idCarrinho` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `quantidade` DECIMAL(100) NULL,
  `price` DECIMAL(100,2) NULL,
  `totalPrice` DECIMAL(100,2) NULL,
  `idPerfil` INT NULL,
  PRIMARY KEY (`idCarrinho`),
  INDEX `idProduct_idx` (`idProduct` ASC) VISIBLE,
  INDEX `idUsuario_idx` (`idPerfil` ASC) VISIBLE,
  CONSTRAINT `idProduct`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `mydb`.`PerfilCompleto` (`idPerfil Completo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_pagto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_pagto` (
  `idtipo_pagto` INT NOT NULL,
  `nome_pagto` VARCHAR(100) NULL,
  PRIMARY KEY (`idtipo_pagto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `idCarrinho` INT NOT NULL,
  `idPagamento` INT NOT NULL,
  `Confirm` VARCHAR(100) NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `idCarrinho_idx` (`idCarrinho` ASC) VISIBLE,
  INDEX `idPagamento_idx` (`idPagamento` ASC) VISIBLE,
  CONSTRAINT `idCarrinho`
    FOREIGN KEY (`idCarrinho`)
    REFERENCES `mydb`.`Carrinho` (`idCarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPagamento`
    FOREIGN KEY (`idPagamento`)
    REFERENCES `mydb`.`tipo_pagto` (`idtipo_pagto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `idstatus` INT NOT NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `idPedido` INT NULL,
  `idstatus` INT NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `data_status` TIMESTAMP NULL,
  PRIMARY KEY (`idEntrega`),
  INDEX `idstatus_idx` (`idstatus` ASC) VISIBLE,
  INDEX `idPedido_idx` (`idPedido` ASC) VISIBLE,
  CONSTRAINT `idPedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idstatus`
    FOREIGN KEY (`idstatus`)
    REFERENCES `mydb`.`status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
